[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel",
{%- if cookiecutter._setup_py_uses_setuptools_scm == 'yes' %}
    "setuptools_scm>=3.3.1{% if cookiecutter._legacy_python == 'yes' %},<6.0{% endif %}",
{%- endif %}
{%- if cookiecutter._c_extension_support == 'cffi' %}
    "cffi>=1.0.0",
{%- endif %}
]
{%- if cookiecutter._pre_commit_formatter == 'black' %}

[tool.black]
line-length = 140
target-version = ['{% if cookiecutter._legacy_python == "yes" %}py27{% else %}py36{% endif %}']
skip-string-normalization = true
{%- elif cookiecutter._pre_commit_formatter == 'blue' %}

[tool.blue]
line-length = 140
target-version = ['{% if cookiecutter._legacy_python == "yes" %}py27{% else %}py36{% endif %}']
skip-string-normalization = true
{%- endif %}
